# This is the kernel build action

name: build-kernel

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only if kernel config is updated
  push:
    paths:
      - "kernel/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Just in ubuntu is too old, just install prebuilt for now.
      - name: install deps
        run: |
          sudo apt update
          sudo apt install -y repo
          sudo cp just/just-x86_64 /usr/bin/just

      # Runs a set of commands using the runners shell
      - name: Compile kernel
        run: |
          just build_kernel
      - uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: kernel/out/